    Title "IP8-5 16Bit Multiplication"
	List p=18F452, f =inhx32
	#include <p18F452.inc>	;The header file 

NUM1LO	EQU		0x02
NUM1HI	EQU		0x01
NUM2LO	EQU		0x05
NUM2HI	EQU		0x02

WORD1		SET		0x10
WORD2		SET		0x20
RESULT		SET		0x30


SECT0:	MOVLW	NUM1LO
		MOVWF	WORD1		
		MOVLW	NUM1HI
		MOVWF	WORD1+ 1
		MOVLW	NUM2LO
		MOVWF	WORD2		
		MOVLW	NUM2HI
		MOVWF	WORD2+ 1

SECT1:	MOVF	WORD1,W			;NUM1LO x NUM2LO 
		MULWF	WORD2
		MOVFF	PRODL, RESULT		;Save result 
		MOVFF	PRODH, RESULT+1
		
SECT2:	MOVF	WORD1+1,W		;NUM1HI x NUM2HI 
		MULWF	WORD2+1
		MOVFF	PRODL, RESULT+2	;Save result 
		MOVFF	PRODH, RESULT+3

SECT3:	MOVF	WORD1+1,W		;NUM1HI x NUM2LO 
		MULWF	WORD2
		MOVF	PRODL,W			;Save result 
		ADDWF	RESULT+1,1
		MOVF	PRODH,W
		ADDWFC	RESULT+2,1
		BTFSC	STATUS, C
		INCF	RESULT+3

SECT4:	MOVF	WORD1,W			;NUM1LO x NUM2HI 
		MULWF	WORD2+1
		MOVF	PRODL,W			;Save result 
		ADDWF	RESULT+1,1
		MOVF	PRODH,W
		ADDWFC	RESULT+2,1
		BTFSC	STATUS, C
		INCF	RESULT+3
		NOP	
		END
