	Title "PIC18F452 Ch13-9 Transmit"
	List p=18F452
	#include <p18F452.inc>	;This is a header file  
							

TRANSMT:CALL		BUS_CHK
		MOVLW		0x41
		CALL		SEND_BYTE
HERE:	BRA			HERE
BUS_CHK	MOVF		SSPCON2, WREG
		ANDLW		B'00011111'
		BNZ			BUS_CHK
CHK_WR	BTFSC		SSPSTAT,R_W
		BRA			CHK_WR
		RETURN
SEND_BYTE	
		MOVWF		SSPBUF
CHK_BF	BTFSC		SSPSTAT, BF
		BRA			CHK_BF
		RETURN

		END
	


 
